/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import java.io.IOException;

public class App {


    public static void main(String[] args) throws IOException {
//    this is where we call our methods

        String inputPath = args[0];
        String outputPath = args[1];
        String transform = args[2];


        Bitmap bmp = new Bitmap(inputPath, outputPath, transform);


        bmp.flipVertically();

        bmp.save();

    }
}
